default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: user
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  username: evachan
  password: h1ello
  database: posts_ratings_development

test:
  <<: *default
  username: evachan
  password: h1ello
  database: posts_ratings_test